# Generated by Django 5.1.6 on 2025-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('idioma', models.CharField(max_length=50)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livros')),
            ],
        ),
    ]
